/**
 * Generates output/MASTER_DATA_README.md — the handover document for the
 * Business Analyst and team. Regenerated automatically on every Excel export so
 * the metadata (version, counts, dates) always matches the workbook.
 *
 * Reads version/status from config/version.json (single source of truth) and the
 * authority list from config/authorities.ts, so future changes stay in sync.
 */
import fs from 'fs';
import path from 'path';
import { format } from 'date-fns';
import type { Metadata } from '../config/metadata';
import { AUTHORITIES } from '../config/authorities';
import { logger } from '../utils/logger';

const README_PATH = path.resolve(__dirname, '../../output/MASTER_DATA_README.md');

export function writeMasterDataReadme(meta: Metadata): string {
  const authorityList = AUTHORITIES.map((a) => `- ${a.name}`).join('\n');
  const date = format(meta.generatedDate, 'dd MMM yyyy, HH:mm');
  const verified = format(meta.lastVerified, 'dd MMM yyyy');

  const md = `# Government Schemes & Grants Master Data

> Auto-generated by the Government Data Extraction Engine on ${date}.
> Do not edit by hand — re-run the extractor to regenerate.

| Property | Value |
| --- | --- |
| Dataset Name | ${meta.datasetName} |
| Version | ${meta.version} |
| Status | ${meta.status} |
| Total Schemes | ${meta.totalSchemes} |
| Total Columns | ${meta.totalColumns} |
| Generated Date | ${date} |
| Last Verified | ${verified} |
| Maintained By | ${meta.maintainedBy} |
| Upload Target | ${meta.uploadTarget} |

## Purpose

This Excel workbook (\`government_schemes.xlsx\`) is the **master data source** used
by FirstNest for Australian First Home Buyer government schemes and grants.

The website does **not** use hardcoded scheme information. Instead, an approved
Excel upload becomes the **single source of truth** for all scheme information
shown on the platform. Update the data by generating a new Excel, verifying it,
and uploading it through the Admin Portal.

## Data Source

All information is collected **only from official Australian Government websites**
(\`*.gov.au\`). No third-party or unofficial sources are used.

Authorities:

${authorityList}

## Data Lifecycle

\`\`\`text
Official Government Websites
        ↓
Government Data Extraction Engine
        ↓
government_schemes.xlsx
        ↓
Business Analyst Review
        ↓
Upload through Admin Portal
        ↓
Database Updated
        ↓
Frontend Automatically Displays Updated Data
\`\`\`

## Version Control

Every uploaded Excel represents a **complete snapshot** of government schemes at a
point in time — uploading replaces the previous scheme data in full.

The dataset version is controlled from a single file, \`config/version.json\`. Bump
the \`version\` (and set \`status\` to \`Verified\`) there before handover; the Excel
"Info" sheet and this document update automatically on the next generation.

Recommended fields to track for each upload:

| Field | Example |
| --- | --- |
| Version | ${meta.version} |
| Upload Date | ${verified} |
| Uploaded By | (Business Analyst name) |
| Number of Schemes | ${meta.totalSchemes} |
| Last Verified Date | ${verified} |
| Change Summary | (what changed vs the previous upload) |

## Ownership

| Role | Owner |
| --- | --- |
| Source Owner | Australian Government Authorities |
| Data Verification | Business Analyst |
| System Owner | FirstNest |
| Frontend Data Source | Database populated from approved Excel uploads |

## Update Process

1. Run the extraction engine.
2. Generate the Excel (\`government_schemes.xlsx\`).
3. Review the generated data (see the quality reports in \`output/\`).
4. Verify with the Business Analyst.
5. Upload the approved Excel through the Admin Portal.
6. Existing scheme data is replaced.
7. The frontend automatically reflects the uploaded data.

## Notes

- No third-party websites are used — official \`*.gov.au\` sources only.
- Extraction is **deterministic** (rule-based; no AI/LLM).
- Missing values are intentionally left **blank** rather than guessed.
- **One row represents one government scheme.**
- The Excel is the **single source of truth** for the platform.

## Workbook structure

\`government_schemes.xlsx\` is a **pure master-data file** — a single **Schemes**
worksheet with one row per government scheme (${meta.totalColumns} columns) and no
embedded metadata. All dataset metadata lives in **this document**, not inside the
Excel, so the workbook is ready to upload directly into the Admin Portal.
`;

  const dir = path.dirname(README_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(README_PATH, md, 'utf8');
  logger.ok(`Wrote master-data README → ${README_PATH}`);
  return README_PATH;
}

export { README_PATH };
